name = "MaximumScoreEstimation"
uuid = "566ffa90-5c03-43fc-acc9-88e6ced28985"
authors = ["James Atkins <james@jamesatkins.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
